# Generated by Django 3.0.3 on 2020-04-30 19:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('client_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(blank=True, max_length=63)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(max_length=32767)),
                ('processed', models.TextField(max_length=32767)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measures.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRemoteAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('latest_ip', models.CharField(max_length=63)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measures.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='measures', to='measures.Device')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measures.Measure')),
            ],
        ),
        migrations.CreateModel(
            name='AggregationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measures.Aggregation')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='measures.Log')),
            ],
        ),
    ]
