# Generated by Django 3.0.3 on 2020-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_auto_20200430_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='device',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
